export const adHocSkillsData = [
  "C/C++",
  "Python",
  "MATLAB",
  "ARM Cortex-M",
  "RTOS",
  "Firmware Optimization",
  "Real-time Data Processing",
  "Wireless Communication",
  "Wi-Fi",
  "BLE",
  "Zigbee",
  "IoT",
  "Sensors",
  "PCB Design",
  "Analog Circuit Design",
  "Git",
] as const;
export const smartGridSkillsData = [
  "C/C++",
  "Python",
  "JSON",
  "Linux",
  "Embedded Systems",
  "OCPP",
  "BPL",
  "PLC",
  "7E Protocol",
  "Modbus",
  "Firmware Simulation",
  "Web Simulation",
  "Networking",
  "Multithreading",
  "GDB/JTAG Debugging",
  "Renewable Energy Integration",
] as const;
