export const adHocSkillsData = [
  "C/C++",
  "Python",
  "MATLAB",
  "ARM Cortex-M",
  "RTOS",
  "Firmware Optimization",
  "Real-time Data Processing",
  "Wireless Communication",
  "Wi-Fi",
  "BLE",
  "Zigbee",
  "IoT",
  "Sensors",
  "PCB Design",
  "Analog Circuit Design",
  "Git",
] as const;
export const smartGridSkillsData = [
  "C/C++",
  "Python",
  "JSON",
  "Linux",
  "Embedded Systems",
  "OCPP",
  "BPL",
  "PLC",
  "7E Protocol",
  "Modbus",
  "Firmware Simulation",
  "Web Simulation",
  "Networking",
  "Multithreading",
  "GDB/JTAG Debugging",
  "Renewable Energy Integration",
] as const;

export const bellybandSkillsData = [
  "C/C++",
  "Embedded Firmware",
  "ARM Cortex-M",
  "RTOS",
  "Sensor Fusion",
  "Signal Processing",
  "Motion Detection",
  "Wearable Devices",
  "Low-Power Design",
  "BLE",
  "Wireless Data Transmission",
  "Biomedical Engineering",
  "PCB Design",
  "Prototyping",
  "Data Filtering",
  "Git",
] as const;


export const smartGloveSkillsData = [
  "C/C++",
  "Embedded Firmware",
  "ARM Cortex-M",
  "RTOS",
  "Wearable Devices",
  "Sensor Integration",
  "IMU Sensors",
  "Pressure & Flex Sensors",
  "Sensor Calibration",
  "Signal Processing",
  "Real-Time Data Acquisition",
  "BLE",
  "Wireless Communication",
  "PCB Design",
  "Prototyping",
  "Human-Machine Interaction",
  "Git",
] as const;

export const lipLoftSkillsData = [
  "C/C++",
  "Python",
  "Embedded Systems",
  "Human–Machine Interfaces",
  "Assistive Technology",
  "Puff-and-Sip Interfaces",
  "Real-Time Control Systems",
  "Drone Control",
  "Robotics",
  "Signal Processing",
  "Open-Source Development",
  "System Integration",
  "Rapid Prototyping",
  "Hackathon Development",
  "Team Collaboration",
  "Git",
] as const;

export const smartStentSkillsData = [
  "Biomedical Engineering",
  "MEMS Sensors",
  "RF Antenna Design",
  "Wireless Telemetry",
  "Pressure Sensors",
  "Microfabrication",
  "Embedded Systems",
  "In-Vitro & Ex-Vivo Testing",
  "Device Characterization",
  "Medical Device Prototyping",
  "Human-Centered Design",
  "Signal Processing",
  "Scientific Writing",
  "Peer-Reviewed Publications",
  "Research Leadership",
  "Git",
] as const;

export const smartUreteralStentSkillsData = [
  "Biomedical Engineering",
  "Implantable Medical Devices",
  "MEMS Fabrication",
  "Micro-Pressure Sensors",
  "RF Antenna Design",
  "Wireless Telemetry",
  "In-Vitro & Ex-Vivo Testing",
  "Hydronephrosis Monitoring",
  "Signal Conditioning",
  "Low-Power Electronics",
  "Flexible Electronics",
  "Embedded Systems",
  "C / C++",
  "MATLAB",
  "COMSOL Multiphysics",
  "HFSS",
  "Cleanroom Microfabrication",
  "Device Characterization",
  "Research & Experimental Design",
  "Technical Writing & Publications",
] as const;

export const wifiControllerSkillsData = [
  "Embedded Systems",
  "IoT System Design",
  "STM32",
  "ESP32",
  "WiFi Communication",
  "C / C++",
  "RTOS",
  "Mobile App Integration",
  "Device Scheduling & Automation",
  "Custom PCB Design",
  "Power Management",
  "Embedded Networking",
  "Firmware Development",
  "Enclosure & Product Design",
  "Prototyping & Testing",
  "Git",
] as const;
export const incubatorSkillsData = [
  "Embedded Systems",
  "Medical Device Design",
  "Temperature Sensing",
  "Sensor Calibration",
  "Touchscreen UI",
  "7-inch TFT Display",
  "Embedded GUI Design",
  "C / C++",
  "Real-Time Control",
  "Timing & Scheduling",
  "User Interface Development",
  "Hardware Integration",
  "Power Management",
  "System Testing & Validation",
  "Product Prototyping",
] as const;

export const mp3PlayerSkillsData = [
  "Embedded Systems",
  "STM32",
  "C / C++",
  "Digital Audio Processing",
  "DAC (Digital-to-Analog Conversion)",
  "MMC / SD Card Interface",
  "File System Management",
  "Real-Time Audio Streaming",
  "Audio Signal Output",
  "Amplifier Integration",
  "Low-Level Driver Development",
  "Embedded Firmware Design",
  "Hardware Debugging",
  "System Testing & Validation",
] as const;


export const kneeBraceSkillsData = [
  "Wearable Device Design",
  "Biomedical Engineering",
  "Knee Joint Angle Measurement",
  "EMG (Electromyography)",
  "Biomechanical Signal Processing",
  "Sensor Integration",
  "Embedded Systems",
  "C / C++",
  "Real-Time Data Acquisition",
  "Motion Analysis",
  "Rehabilitation Monitoring",
  "Firmware Development",
  "Hardware Prototyping",
  "System Testing & Validation",
] as const;
